resources:
  limits:
    cpu: 10m
    memory: 40Mi

tolerations:
- key: "node-role.kubernetes.io/control-plane"
  operator: "Exists"
  effect: "NoSchedule"

config:
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Buffer_Size  1Mb

    [FILTER]
        Name           grep
        Match          kube.*
        Exclude        $kubernetes['namespace_name'] metallb-system
        Exclude        $kubernetes['namespace_name'] argocd
        Exclude        $kubernetes['namespace_name'] kube-system
        Exclude        log /^127.0.0.1.*/
        Exclude        log /.*\/metrics.*Prometheus/


  outputs: |
    [OUTPUT]
        Name es
        Match *

        Host elastic-es-http.istio-system.svc.cluster.local
        Port 9200
        Cloud_auth elastic:17Y0gjxE3JIDcW05K730S9lo

        Time_Key  @timestamp
        Index fluent-bit-kube
        Type  _doc

        Suppress_Type_Name On
        Replace_Dots On
        tls.verify off
        Logstash_Format off
        Retry_Limit 2