grafana:
  adminPassword: password
  resources:
    limits:
      cpu: 100m
      memory: 512Mi
  persistence:
    type: pvc
    enabled: true
    storageClassName: nfs-client
    accessModes:
      - ReadWriteOnce
    size: 4Gi
    finalizers:
      - kubernetes.io/pvc-protection
  initChownData:
    enabled: false

  grafana.ini:
    server:
      root_url: http://localhost:3000/grafana
      serve_from_sub_path: true

prometheus:
  prometheusSpec:
    # additionalScrapeConfigs:
    #   - job_name: 'provmox-ve' https://github.com/prometheus-pve/prometheus-pve-exporter
    #     static_configs:
    #       - targets:
    #         - 10.243.100.10
    #     metrics_path: /pve
    #     params:
    #       module: [default]
    #     relabel_configs:
    #       - source_labels: [__address__]
    #         target_label: __param_target
    #       - source_labels: [__param_target]
    #         target_label: instance
    #       - target_label: __address__
    #         replacement: 192.168.100.55:9221
    #   - job_name: 'ubuntu-jumphost'
    #     static_configs:
    #       - targets:
    #         - 192.168.100.55:9100
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-client
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 4Gi
alertmanager:
  enabled: false