grafana:
  adminPassword: password
  resources:
    limits:
      cpu: 100m
      memory: 512Mi
  persistence:
    type: pvc
    enabled: true
    storageClassName: nfs-client
    accessModes:
      - ReadWriteOnce
    size: 4Gi
    finalizers:
      - kubernetes.io/pvc-protection
  initChownData:
    enabled: false

  grafana.ini:
    server:
      root_url: http://k8s.proxmox.local/grafana
      serve_from_sub_path: true
    panels:
      enable_alpha: true
    auth.generic_oauth:
        enabled : true
        name : Keycloak-OIDC
        client_id : grafana-client
        client_secret : 5pphI67RZcQEEcQv73R3TwBw1Ym6GNGv
        scopes : openid email profile offline_access roles
        email_attribute_path : email
        login_attribute_path : username
        name_attribute_path : full_name
        auth_url : http://k8s.proxmox.local/keycloak/realms/oidc/protocol/openid-connect/auth
        token_url : http://k8s.proxmox.local/keycloak/realms/oidc/protocol/openid-connect/token
        api_url :  http://k8s.proxmox.local/keycloak/realms/oidc/protocol/openid-connect/userinfo
        allow_assign_grafana_admin : true
        role_attribute_path : true||'Admin'
prometheus:
  prometheusSpec:
    retention: 5d
    additionalScrapeConfigs:
      - job_name: 'proxmox-ve'
        static_configs:
          - targets:
            - 10.243.100.10:9100
      - job_name: 'ubuntu-jumphost'
        static_configs:
          - targets:
            - 192.168.100.55:9100
      - job_name: 'kong-gateway'
        static_configs:
          - targets: ['kong-gateway-kong-manager.kong-gateway.svc.cluster.local:8001']
      - job_name: 'istiod'
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - istio-system
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: istiod;http-monitoring
      - job_name: 'envoy-stats'
        metrics_path: /stats/prometheus
        kubernetes_sd_configs:
        - role: pod

        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_container_port_name]
          action: keep
          regex: '.*-envoy-prom'

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-client
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 4Gi
alertmanager:
  enabled: false