apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: cluster-addons
  source:
    helm:
      valueFiles:
      - values.yaml
    path: kubernetes/argocd/cluster-bootstrap
    repoURL: https://github.com/guyzsarun/home-server
    targetRevision: chore/improve-bootstrap