version: '3'

services:
  proxmox-exporter:
    image: prompve/prometheus-pve-exporter
    ports:
      - 9221:9221
    restart: always
    environment:
      PYTHONWARNINGS: "ignore:Unverified HTTPS request"
      PVE_VERIFY_SSL: "false"
      PVE_MODULE: default
      PVE_USER:
      PVE_PASSWORD: