apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    pilot:
      k8s:
        resources:
          requests:
            cpu: 50m
            memory: 128m
          limits:
            memory: 1G
        hpaSpec:
          maxReplicas: 2
          minReplicas: 1
