apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-essentials
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/default-gateway
  http:
  - match:
    - uri:
        prefix: /jaeger
    route:
    - destination:
        port:
          number: 80
        host: tracing.istio-system.svc.cluster.local
  - match:
    - uri:
        prefix: /kiali
    headers:
      request:
        set:
          X-Forwarded-Port: "443"
    route:
    - destination:
        port:
          number: 20001
        host: kiali.istio-system.svc.cluster.local
  - match:
    - uri:
        prefix: /prometheus/
    - uri:
        prefix: /prometheus
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 9090
        host: monitoring-kube-prometheus-prometheus.istio-system.svc.cluster.local
  - match:
    - uri:
        prefix: /grafana
    route:
    - destination:
        port:
          number: 80
        host: monitoring-grafana.istio-system.svc.cluster.local
  - match:
    - uri:
        prefix: /keycloak
    route:
    - destination:
        port:
          number: 8080
        host: keycloak.authentication.svc.cluster.local
  - match:
    - uri:
        prefix: /kibana
    route:
    - destination:
        host: kibana-kb-http.istio-system.svc.cluster.local
        port:
          number: 5601