version: '3'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-02-04T22-36-13Z-cpuv1
    ports:
      - "9000:9000"
      - "9090:9090"
    restart: always
    hostname: server.proxmox.local
    volumes:
      - /mnt/nfs_share/minio:/data
      - /home/devops/certs/proxmox.local.pem:/root/.minio/certs/CAs/myCA.crt:ro
      - /home/devops/certs/server.proxmox.local.pem:/root/.minio/certs/public.crt:ro
      - /home/devops/certs/server.proxmox.local.key:/root/.minio/certs/private.key:ro
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: P@ssw0rd
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_SERVER_URL: https://server.proxmox.local:9000
      MINIO_BROWSER_REDIRECT_URL: https://server.proxmox.local:9090
      MINIO_IDENTITY_OPENID_CONFIG_URL: "https://k8s.proxmox.local/keycloak/realms/keycloak-oidc/.well-known/openid-configuration"
      MINIO_IDENTITY_OPENID_CLIENT_ID: "minio-openid-client"
      MINIO_IDENTITY_OPENID_CLIENT_SECRET: "mRhvqhigsF38FUVSOpLIqt38g534jFaW"
      MINIO_IDENTITY_OPENID_SCOPES: "openid,profile,email"
      MINIO_IDENTITY_OPENID_DISPLAY_NAME: "Keycloak OIDC Login"
    command: server --certs-dir "/root/.minio/certs" --console-address ":9090" /data