manager:
  enabled: true
  type: LoadBalancer
  tls:
    enabled: false
  http:
    enabled: true
    servicePort: 80
    containerPort: 8002

admin:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
  tls:
    enabled: false

proxy:
  tls:
    enabled: false

env:
  prefix: /kong_prefix/
  database: "postgres"
  pg_host: "postgres-db.authentication.svc.cluster.local"
  pg_port: 5432
  pg_user: "postgres"
  pg_password: "password"
  pg_database: "kong"
  pg_ssl: "off"
  pg_ssl_verify: "off"


extraObjects:
- apiVersion: configuration.konghq.com/v1
  kind: KongClusterPlugin
  metadata:
    name: prometheus
    annotations:
      kubernetes.io/ingress.class: kong
    labels:
      global: 'true'
  config:
    per_consumer: true
    status_code_metrics: true
    latency_metrics: true
    bandwidth_metrics: true
    upstream_health_metrics: true
  plugin: prometheus
