---
- name: Install Server
  hosts: ubuntu-server
  vars:
    HARBOR_VERSION: v2.8.2

  tasks:
  - name: Install essentials
    become: true
    apt:
      name:
        - docker
        - net-tools
        - gpg
        - docker-compose
      state: present
      update_cache: yes
    tags:
    - always
  - name: Install, Config Harbor
    tags: harbor
    block:
      - unarchive:
          src: https://github.com/goharbor/harbor/releases/download/{{ HARBOR_VERSION }}/harbor-offline-installer-{{ HARBOR_VERSION }}.tgz
          dest: /tmp
          remote_src: yes
      - copy:
          src: /tmp/harbor
          remote_src: true
          dest: /home/devops
      - copy:
          src: ./config/
          dest: /home/devops/harbor
  - name: Install, Config minio
    tags: minio
    block:
      - file:
          path: /home/devops/minio/data
          state: directory
      - copy:
          src: ./config/minio.yaml
          dest: /home/devops/minio
      - become: true
        shell: |
          cd /home/devops/minio
          docker-compose -f minio.yaml up -d
  - name: Install, Config vault
    tags: vault
    block:
      - become: true
        shell: |
            wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --yes --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      - become: true
        apt:
          name:
            - vault=1.4.*
          state: present
          update_cache: yes