apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
spec:
  version: 8.10.4
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  # secureSettings:
  # - secretName: elastic-keycloak-secret
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
      xpack:
        security:
          enabled: true
      #     authc:
      #       token.enabled: true
      #       realms:
      #         oidc:
      #           oidc:
      #             order: 2
      #             rp.client_id: "elk-client"
      #             rp.response_type: "code"
      #             rp.requested_scopes: ["openid", "email"]
      #             rp.redirect_uri: "https://kibana-kb-http.elastic-system.svc.cluster.local:5601/api/security/v1/oidc"
      #             op.issuer: "http://k8s.proxmox.local/keycloak/realms/oidc"
      #             op.authorization_endpoint: "http://k8s.proxmox.local/keycloak/realms/oidc/protocol/openid-connect/auth"
      #             op.token_endpoint: "http://k8s.proxmox.local/keycloak/realms/oidc/protocol/openid-connect/token"
      #             op.userinfo_endpoint: "http://k8s.proxmox.local/keycloak/realms/oidc/protocol/openid-connect/userinfo"
      #             op.endsession_endpoint: "http://k8s.proxmox.local/keycloak/realms/oidc/protocol/openid-connect/logout"
      #             op.jwkset_path: "http://k8s.proxmox.local/keycloak/realms/oidc/protocol/openid-connect/certs"
      #             claims.principal: name
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 1.5Gi
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: elastic-keycloak-secret
# type: Opaque
# data:
#   xpack.security.authc.realms.oidc.oidc.rp.client_secret: "iFP0tHUBaYwUC1dOWAX1xr5BpTpXshxy"