resources:
  limits:
    cpu: 10m
    memory: 40Mi

tolerations:
- key: "node-role.kubernetes.io/control-plane"
  operator: "Exists"
  effect: "NoSchedule"

config:
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Buffer_Size  1Mb

    [FILTER]
        Name           grep
        Match          kube.*
        Exclude        $kubernetes['namespace_name'] metallb-system

  outputs: |
    [OUTPUT]
        Name es
        Match *

        Host elastic-es-http.istio-system.svc.cluster.local
        Cloud_auth elastic:17Y0gjxE3JIDcW05K730S9lo

        Index fluent-bit-kube
        Replace_Dots On
        Port 9200
        Logstash_Format off
        Suppress_Type_Name On
        Time_Key  @timestamp
        Retry_Limit 2
        tls.verify Off
        Type  _doc
