name: healthcheck

on:
  workflow_dispatch:
  # schedule:
  # - cron: "0 0 * * *"

env:
  HOSTS: '
    proxmox:10.243.100.160
    '


jobs:
  healthcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: zerotier login
      uses: zerotier/github-action@v1.0.1
      with:
        network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
        auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

    - name: ping host
      shell: bash
      run: |
        sleep 15 ;
        for lines in ${{ env.HOSTS }};
        do
          line=($(echo $lines | awk -F ':' '{print $1,$2}'))
          echo ${line[0]}
          ping -i 2 -W 4 -c 20 ${line[1]}
        done
