name: healthcheck

on:
  workflow_dispatch:
  push:
  schedule:
  - cron: "0 7 * * *"

env:
  HOSTS: '
    proxmox:10.243.100.10
    jumphost:10.243.100.143
    '

jobs:
  healthcheck:
    runs-on: ubuntu-latest
    steps:
    # - name: zerotier login
    #   uses: zerotier/github-action@v1.0.1
    #   with:
    #     network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
    #     auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

    - name: ping host
      shell: bash
      run: |
        read -a array <<< ${{ env.HOSTS }}
        for lines in "${array[@]}";
        do
          echo ee $lines
          # line=($(echo $lines | awk -F ':' '{print $1,$2}'))
          # echo ${line[1]}
          # echo ${line[2]}
        done
