name: main

on:
  push:

  workflow_dispatch:

jobs:
  pakcer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: validate
        run: cd packer && packer validate .

  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: init
        run: terraform init

      - name: validate
        run: terraform validate

