name: main

on:
  push:

  workflow_dispatch:

jobs:
  packer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "cd packer && packer init ."

      - name: Run `packer validate`
        id: validate
        run: "cd packer && packer validate ."

  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: init
        run: terraform init

      - name: validate
        run: terraform validate

