name: main

on:
  push:
    branches:
    - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
  workflow_dispatch:

jobs:
  packer:
    runs-on: ubuntu-latest
    container: hashicorp/packer:1.9

    steps:
      - uses: actions/checkout@v3

      - name: Run `packer init`
        id: init
        run: "cd packer && packer init ."

      - name: Run `packer validate`
        id: validate
        run: "cd packer && packer validate ."

  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Init
        run: terraform -chdir=./terraform init

      - name: Validate
        run: terraform -chdir=./terraform validate

      - name: Linting
        run: terraform -chdir=./terraform fmt -recursive -check

