name: main

on:
  push:
    branches:
    - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
  workflow_dispatch:

env:
  K8S_IGNORE_LINT: 'argocd.yaml\|istio\|kong\|elastic\|kibana\|values'
  TERRAFORM_COMMAND: 'terraform -chdir=./terraform'

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Glob kubernetes yaml
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "YAML_LIST<<$EOF" >> "$GITHUB_ENV"
          ls -1Rd kubernetes/*/*.yaml  | grep -v ${K8S_IGNORE_LINT} >> "$GITHUB_ENV"
          echo "$EOF" >> "$GITHUB_ENV"
      - name: kubernetes lint
        uses: azure/k8s-lint@v1
        with:
           manifests: |
              ${{ env.YAML_LIST }}
  packer:
    runs-on: ubuntu-latest
    container: hashicorp/packer:1.9
    steps:
      - uses: actions/checkout@v3

      - name: Run `packer init`
        id: init
        run: "cd packer && packer init ."

      - name: Run `packer validate`
        id: validate
        run: "cd packer && packer validate ."

  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Init
        run: ${TERRAFORM_COMMAND} init

      - name: Linting
        run: ${TERRAFORM_COMMAND} fmt -recursive -check

      - name: Validate
        run: ${TERRAFORM_COMMAND} validate
